### PR TITLE
Ignore .init section error.

### PR DESCRIPTION
**Pull request by Icaro-Lima**
Resolves an error that occurs following the Manual Installation.

### CODE REVIEW

**Comment by schaars** [comment]
Hi

Thank you for the commit. As we never encounter this error, do you know what is triggering it, what is the problem without this flag and what is solves?

**Comment by Icaro-Lima** [comment]
Without this flag gives this error:
```
...
<!-- Please refer to User's Guide for the explanation of each field -->
<EnclaveConfiguration>
    <ProdID>0</ProdID>
    <ISVSVN>0</ISVSVN>
    <StackMaxSize>0x40000</StackMaxSize>
    <HeapMaxSize>0x4600000</HeapMaxSize>
    <TCSNum>50</TCSNum>
    <TCSPolicy>1</TCSPolicy>
    <DisableDebug>0</DisableDebug>
    <MiscSelect>0</MiscSelect>
    <MiscMask>0xFFFFFFFF</MiscMask>
</EnclaveConfiguration>
The enclave image has .init section.
Error happened while signing the enclave.
Makefile.sgx:828: recipe for target 'signed_enclave' failed
make: *** [signed_enclave] Error 255
```
See the `sgx_sign --help`:

> -ignore-init-sec-error 
> By default, sgx_sign provides an error for enclaves with .init section.
>                            You can ignore the error and continue signing by providing this option.
>                            But it is recommended you eliminate the section instead of bypassing
>                            the error with this option.

**Comment by Icaro-Lima** [comment]
Look here:
[Actual linux-sgx](https://github.com/intel/linux-sgx/blob/master/sdk/sign_tool/SignTool/util_st.h)

And here:
[Older linux-sgx version, 1.8](https://github.com/intel/linux-sgx/blob/sgx_1.8/sdk/sign_tool/SignTool/util_st.h)

You use a version a little newer than 1.8, but still, to see that before did not have the flag to ignore the `.init`.

**Comment by schaars** [comment]
Maybe this is a stupid question, but what's wrong with having a `.init` section inside the enclave?

**Comment by Icaro-Lima** [comment]
Você realmente vê para ver:
https://github.com/intel/intel-sgx-ssl/blob/master/Linux/package/docs/Intel(R)%20Software%20Guard%20Extensions%20SSL%20Library%20Linux%20Developer
% 20Guide.pdf

Topic 3.

**Comment by Icaro-Lima** [comment]
ignore this email, I'll send another one soon

**Pull request closed without merging**
